name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: PYTHONPATH=. pytest tests/test_api.py

      - name: Deploy to Hugging Face Spaces
        if: success()
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/monganio/mlop
          git push space main --force