name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: PYTHONPATH=. pytest tests/test_api.py

      - name: Deploy to Hugging Face Spaces
        if: success()
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. ตั้งค่า Git เบื้องต้น
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 2. ทำลายประวัติเก่าที่มีไฟล์ขนาดใหญ่ทิ้ง (ลบ .git folder ของ runner)
          rm -rf .git
          
          # 3. เริ่มนับหนึ่งใหม่ (สร้างประวัติ Git ใหม่ที่มีเฉพาะไฟล์ปัจจุบัน)
          git init
          git add .
          git commit -m "Deploy optimized model: Quantized version"
          
          # 4. บังคับส่งงานไปที่ Hugging Face (จาก master ของ runner ไปที่ main ของ Space)
          git remote add space https://monganio:$HF_TOKEN@huggingface.co/spaces/monganio/mlop
          git push space master:main --force